# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Avarwand.AGm
PackageVersion: 1.4.75.1
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/avarwand/AGm/releases/download/wgagm/AGm-1.4.75.1-Setup-x64.msi
  InstallerSha256: 311C138FE3B982C662F1167D7A60B7021E06CE85FF256A06330A55CAA95A2782
ManifestType: installer
ManifestVersion: 1.6.0
