# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Avarwand.AGm
PackageVersion: 1.4.75.1
PackageLocale: en-US
Publisher: Avarwand
PublisherUrl: https://github.com/avarwand
PublisherSupportUrl: https://github.com/avarwand/AGm/issues
PrivacyUrl: https://github.com/avarwand/
Author: Avarwand Software
PackageName: AGm
PackageUrl: https://github.com/avarwand/AGm
License: EULA
LicenseUrl: https://github.com/avarwand/AGm/blob/master/LICENSE.md
Copyright: Avarwand
CopyrightUrl: https://github.com/avarwand/AGm/blob/master/LICENSE.md
ShortDescription: A professional graphical Git repository manager, designed to manage multiple Repositories simultaneously (includes automating batch logging, staging, committing, tagging and pushing), and more features.
Description: A professional graphical Git repository manager, designed to manage multiple local Git repositories simultaneously (includes automating batch logging, staging, committing, tagging and pushing), with batch operations, live status monitoring and live progress tracking, without ever touching the command line, although there is an interactive CLI.
Moniker: agm
Tags:
- AGm
- agm
- Avarwand Git manager
- git manager
- gui git
- gui git manager
- avarwand tool
- window git
ReleaseNotes: initial public release
ReleaseNotesUrl: https://github.com/avarwand/AGm/releases/tag/v1.4.75.1
ManifestType: defaultLocale
ManifestVersion: 1.6.0
